import os
os.system ('clear')
print("           HELLO IN STONE TOOL")
print("                   ")
print("Type on the tool number to download it..!")
print("                                         ")
print("==================================")
print("whatapp number:+20 01011485721")
print("follow me in youtube chanal:LAZLO YT")
print("github:3mk5mr")
print("efa whatsapp number:+20 101 427 6342")
print("A5oya whats app number:+20 100 116 1898")
print("NEWTON whatsapp number:+20 115 195 3145")
print("==================================")
print("┈╭━━━━━━━━━━━╮┈")
print("╭╯┈╭━━╮┈╭━━╮┈╰╮")
print("┃┈┃┃╭╮┃┈┃╭╮┃┃┈┃")
print("┃┈┃┻┻┻┛┈┗┻┻┻┃┈┃")
print("┃┈┃╭╮┈◢▇◣┈╭╮┃┈┃") 
print("╰┳╯┃╰━━┳┳┳╯┃╰┳╯") 
print("┈┃┈╰━━━┫┃┣━╯┈┃┈")
print("┈┃┈┈┈┈┈╰━╯┈┈┈┃┈")
print("==================================")
print("1-install metasoplit")
print("2-install OSIF")
print("3-install HXwhatsapp")
print("4-install Hackcamera")
print("5-install search xss")
print("6-install ipcs")
print("7-install TmX-FW")
print("8-install LedarHack")
print("9-install BRUTEFORCEnew")
print("10-install A-Rat")
print("==================================")
print("{☹◈STONE◈☻}━▷")


